# Generated by Django 6.0.6 on 2026-06-12 15:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        help_text="MIME type, e.g. image/png", max_length=100
                    ),
                ),
                ("size_bytes", models.PositiveIntegerField()),
                ("file", models.URLField()),
                (
                    "storage_key",
                    models.CharField(
                        blank=True,
                        help_text="Object storage key/path for provider-independent access.",
                        max_length=1024,
                    ),
                ),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("content_id", models.CharField(blank=True, max_length=255, null=True)),
                ("content_disposition", models.CharField(blank=True, max_length=100)),
                ("is_inline", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Email Attachment",
                "verbose_name_plural": "Email Attachments",
                "db_table": "emails_attachment",
            },
        ),
        migrations.CreateModel(
            name="EmailLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", help_text="Hex color code", max_length=7
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Email Label",
                "verbose_name_plural": "Email Labels",
                "db_table": "emails_label",
            },
        ),
        migrations.CreateModel(
            name="EmailMessageLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "emails_messagelabel",
            },
        ),
        migrations.CreateModel(
            name="EmailMessageUserState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "folder",
                    models.CharField(
                        choices=[
                            ("inbox", "Inbox"),
                            ("sent", "Sent"),
                            ("drafts", "Drafts"),
                            ("spam", "Spam"),
                            ("archive", "Archive"),
                            ("trash", "Trash"),
                        ],
                        db_index=True,
                        default="inbox",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("is_starred", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Message User State",
                "verbose_name_plural": "Email Message User States",
                "db_table": "emails_messageuserstate",
            },
        ),
        migrations.CreateModel(
            name="EmailRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("to", "To"),
                            ("cc", "Cc"),
                            ("bcc", "Bcc"),
                            ("reply_to", "Reply-To"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("provider_recipient_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("bounced", "Bounced"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("spam", "Spam"),
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("failed", "Failed"),
                            ("received", "Received"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=15,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Recipient",
                "verbose_name_plural": "Email Recipients",
                "db_table": "emails_recipient",
                "ordering": ["recipient_type", "email"],
            },
        ),
        migrations.CreateModel(
            name="EmailThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=998, null=True)),
                ("normalized_subject", models.CharField(blank=True, max_length=998)),
                (
                    "root_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Message-ID that started the conversation, when known.",
                        max_length=255,
                    ),
                ),
                ("participants", models.JSONField(default=list)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("has_unread", models.BooleanField(db_index=True, default=True)),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Email Thread",
                "verbose_name_plural": "Email Threads",
                "db_table": "emails_thread",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Mailbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "local_part",
                    models.CharField(
                        help_text="Part before the @. E.g. 'john' for john@acme.com",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use only a valid email local-part, without the @domain.",
                                regex="^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Friendly sender name shown in email clients",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "is_catch_all",
                    models.BooleanField(
                        default=False,
                        help_text="Receives mail sent to any unmatched address on this domain",
                    ),
                ),
                (
                    "forward_to",
                    models.EmailField(
                        blank=True,
                        help_text="If set, incoming mail is also forwarded to this external address",
                        max_length=254,
                    ),
                ),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("send_enabled", models.BooleanField(default=True)),
                ("receive_enabled", models.BooleanField(default=True)),
                (
                    "quota_bytes",
                    models.BigIntegerField(
                        default=0,
                        help_text="0 = unlimited. Enforce while storing inbound mail and attachments.",
                    ),
                ),
                ("used_bytes", models.BigIntegerField(default=0)),
                ("signature_html", models.TextField(blank=True)),
                ("signature_text", models.TextField(blank=True)),
                (
                    "provider_sender_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider-side sender or stream identifier if applicable.",
                        max_length=255,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mailbox",
                "verbose_name_plural": "Mailboxes",
                "db_table": "mailboxes_mailbox",
            },
        ),
        migrations.CreateModel(
            name="MailboxAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "local_part",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use only a valid email local-part, without the @domain.",
                                regex="^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+$",
                            )
                        ],
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("can_send", models.BooleanField(default=True)),
                ("can_receive", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mailbox Alias",
                "verbose_name_plural": "Mailbox Aliases",
                "db_table": "mailboxes_alias",
                "ordering": ["domain__name", "local_part"],
            },
        ),
        migrations.CreateModel(
            name="MailboxRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Rule predicates, e.g. from_contains, subject_contains, has_attachment.",
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        default=dict,
                        help_text="Rule actions, e.g. add_label, move_to_folder, forward_to.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mailbox Rule",
                "verbose_name_plural": "Mailbox Rules",
                "db_table": "mailboxes_rule",
                "ordering": ["mailbox", "priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="OutboundSendAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Outbound Send Attempt",
                "verbose_name_plural": "Outbound Send Attempts",
                "db_table": "emails_outboundsendattempt",
                "ordering": ["message_id", "attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="SenderIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("signature_html", models.TextField(blank=True)),
                ("signature_text", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sender Identity",
                "verbose_name_plural": "Sender Identities",
                "db_table": "mailboxes_senderidentity",
                "ordering": ["mailbox__local_part", "email"],
            },
        ),
        migrations.CreateModel(
            name="SuppressedAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("reason", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="unsubscribe, bounce, complaint, admin, import, etc.",
                        max_length=100,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Suppressed Address",
                "verbose_name_plural": "Suppressed Addresses",
                "db_table": "emails_suppressedaddress",
            },
        ),
        migrations.CreateModel(
            name="UserMailboxAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("mailbox", "Mailbox Access"),
                            ("domain", "Domain Access"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("read_only", "Read Only"),
                            ("read_write", "Read & Write"),
                            ("full_access", "Full Access"),
                        ],
                        default="read_write",
                        max_length=15,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. Access auto-expires after this datetime.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "User Mailbox Access",
                "verbose_name_plural": "User Mailbox Accesses",
                "db_table": "mailboxes_usermailboxaccess",
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("bounced", "Bounced"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("spam", "Spam"),
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("failed", "Failed"),
                            ("received", "Received"),
                        ],
                        default="received",
                        max_length=15,
                    ),
                ),
                (
                    "folder",
                    models.CharField(
                        choices=[
                            ("inbox", "Inbox"),
                            ("sent", "Sent"),
                            ("drafts", "Drafts"),
                            ("spam", "Spam"),
                            ("archive", "Archive"),
                            ("trash", "Trash"),
                        ],
                        db_index=True,
                        default="inbox",
                        max_length=10,
                    ),
                ),
                (
                    "rfc_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Value of the Message-ID header (RFC 2822)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("from_address", models.EmailField(max_length=254)),
                ("from_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "envelope_sender",
                    models.EmailField(
                        blank=True,
                        help_text="SMTP MAIL FROM / return-path address.",
                        max_length=254,
                    ),
                ),
                (
                    "envelope_recipient",
                    models.EmailField(
                        blank=True,
                        help_text="SMTP RCPT TO that caused delivery to this mailbox.",
                        max_length=254,
                    ),
                ),
                (
                    "to_addresses",
                    models.JSONField(
                        default=list,
                        help_text='List of dicts: [{"email": "...", "name": "..."}]',
                    ),
                ),
                ("cc_addresses", models.JSONField(default=list)),
                ("bcc_addresses", models.JSONField(default=list)),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=998)),
                (
                    "in_reply_to",
                    models.CharField(
                        blank=True,
                        help_text="RFC 2822 In-Reply-To header value",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True,
                        help_text="Space-separated list of referenced Message-IDs",
                        null=True,
                    ),
                ),
                (
                    "body_text",
                    models.TextField(blank=True, help_text="Plain-text part"),
                ),
                ("body_html", models.TextField(blank=True, help_text="HTML part")),
                ("snippet", models.CharField(blank=True, max_length=500)),
                (
                    "raw_headers",
                    models.JSONField(
                        default=dict,
                        help_text="All raw MIME headers preserved for debugging / compliance",
                    ),
                ),
                (
                    "raw_mime_url",
                    models.URLField(
                        blank=True,
                        help_text="Object-storage URL for the raw MIME source, if retained.",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider-assigned ID (for delivery tracking / webhooks)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("is_starred", models.BooleanField(default=False)),
                ("has_attachments", models.BooleanField(default=False)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "spam_score",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Message",
                "verbose_name_plural": "Email Messages",
                "db_table": "emails_message",
                "ordering": ["-created_at"],
            },
        ),
    ]
