# Generated by Django 6.0.6 on 2026-06-12 15:22

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hedwig", "0001_initial"),
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Provider that sent or received this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="providers.emailprovider",
            ),
        ),
        migrations.AddField(
            model_name="emailattachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="hedwig.emailmessage",
            ),
        ),
        migrations.AddField(
            model_name="emailmessagelabel",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_labels",
                to="hedwig.emaillabel",
            ),
        ),
        migrations.AddField(
            model_name="emailmessagelabel",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_labels",
                to="hedwig.emailmessage",
            ),
        ),
        migrations.AddField(
            model_name="emailmessageuserstate",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_states",
                to="hedwig.emailmessage",
            ),
        ),
        migrations.AddField(
            model_name="emailmessageuserstate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_states",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailrecipient",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="hedwig.emailmessage",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="hedwig.emailthread",
            ),
        ),
        migrations.AddField(
            model_name="mailbox",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailboxes",
                to="providers.domain",
            ),
        ),
        migrations.AddField(
            model_name="emailthread",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="hedwig.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="emailrecipient",
            name="delivered_to_mailbox",
            field=models.ForeignKey(
                blank=True,
                help_text="Mailbox this recipient mapped to for inbound delivery.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivered_recipient_rows",
                to="hedwig.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="hedwig.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="emaillabel",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="hedwig.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="mailboxalias",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailbox_aliases",
                to="providers.domain",
            ),
        ),
        migrations.AddField(
            model_name="mailboxalias",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="hedwig.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="mailboxrule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailbox_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mailboxrule",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="hedwig.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="outboundsendattempt",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="send_attempts",
                to="hedwig.emailmessage",
            ),
        ),
        migrations.AddField(
            model_name="outboundsendattempt",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="send_attempts",
                to="providers.emailprovider",
            ),
        ),
        migrations.AddField(
            model_name="senderidentity",
            name="alias",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_identities",
                to="hedwig.mailboxalias",
            ),
        ),
        migrations.AddField(
            model_name="senderidentity",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_identities",
                to="hedwig.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="sender_identity",
            field=models.ForeignKey(
                blank=True,
                help_text="Identity selected for outbound mail.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="hedwig.senderidentity",
            ),
        ),
        migrations.AddField(
            model_name="suppressedaddress",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppressed_addresses",
                to="providers.domain",
            ),
        ),
        migrations.AddField(
            model_name="suppressedaddress",
            name="mailbox",
            field=models.ForeignKey(
                blank=True,
                help_text="Blank means the suppression applies to the whole domain.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppressed_addresses",
                to="hedwig.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="suppressedaddress",
            name="raw_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suppressed_addresses",
                to="providers.providerwebhooklog",
            ),
        ),
        migrations.AddField(
            model_name="usermailboxaccess",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_accesses",
                to="providers.domain",
            ),
        ),
        migrations.AddField(
            model_name="usermailboxaccess",
            name="granted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usermailboxaccess",
            name="mailbox",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_accesses",
                to="hedwig.mailbox",
            ),
        ),
        migrations.AddField(
            model_name="usermailboxaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailbox_accesses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(
                fields=["message", "is_inline"], name="emails_atta_message_12a05c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(
                fields=["checksum_sha256"], name="emails_atta_checksu_91e12c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailmessagelabel",
            constraint=models.UniqueConstraint(
                fields=("message", "label"), name="unique_message_label"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessageuserstate",
            index=models.Index(
                fields=["user", "folder", "-updated_at"],
                name="emails_mess_user_id_4a9eaf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessageuserstate",
            index=models.Index(
                fields=["user", "is_read"], name="emails_mess_user_id_75b7da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessageuserstate",
            index=models.Index(
                fields=["snoozed_until"], name="emails_mess_snoozed_ee1a54_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailmessageuserstate",
            constraint=models.UniqueConstraint(
                fields=("user", "message"), name="unique_user_message_state"
            ),
        ),
        migrations.AddIndex(
            model_name="mailbox",
            index=models.Index(
                fields=["domain", "is_active"], name="mailboxes_m_domain__762421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailbox",
            index=models.Index(
                fields=["domain", "is_catch_all"], name="mailboxes_m_domain__e43133_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mailbox",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("local_part"),
                models.F("domain"),
                name="unique_mailbox_per_domain",
            ),
        ),
        migrations.AddIndex(
            model_name="emailthread",
            index=models.Index(
                fields=["mailbox", "-last_message_at"],
                name="emails_thre_mailbox_5b7eff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailthread",
            index=models.Index(
                fields=["mailbox", "has_unread"], name="emails_thre_mailbox_a33280_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailrecipient",
            index=models.Index(
                fields=["message", "recipient_type"],
                name="emails_reci_message_47a2eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailrecipient",
            index=models.Index(
                fields=["email", "status"], name="emails_reci_email_203caa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emaillabel",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "name"), name="unique_label_per_mailbox"
            ),
        ),
        migrations.AddIndex(
            model_name="mailboxalias",
            index=models.Index(
                fields=["domain", "is_active"], name="mailboxes_a_domain__b9f8a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailboxalias",
            index=models.Index(
                fields=["mailbox", "is_active"], name="mailboxes_a_mailbox_abb425_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mailboxalias",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("local_part"),
                models.F("domain"),
                name="unique_alias_per_domain",
            ),
        ),
        migrations.AddIndex(
            model_name="mailboxrule",
            index=models.Index(
                fields=["mailbox", "is_active", "priority"],
                name="mailboxes_r_mailbox_80db06_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailboxrule",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "name"), name="unique_rule_name_per_mailbox"
            ),
        ),
        migrations.AddIndex(
            model_name="outboundsendattempt",
            index=models.Index(
                fields=["provider", "status", "created_at"],
                name="emails_outb_provide_5a4ef8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outboundsendattempt",
            index=models.Index(
                fields=["provider_message_id"], name="emails_outb_provide_b0ec0e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundsendattempt",
            constraint=models.UniqueConstraint(
                fields=("message", "attempt_number"), name="unique_send_attempt_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundsendattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("provider", "idempotency_key"),
                name="unique_provider_send_idempotency_key",
            ),
        ),
        migrations.AddIndex(
            model_name="senderidentity",
            index=models.Index(
                fields=["mailbox", "is_active"], name="mailboxes_s_mailbox_8f2791_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="senderidentity",
            constraint=models.UniqueConstraint(
                models.F("mailbox"),
                django.db.models.functions.text.Lower("email"),
                name="unique_sender_identity_per_mailbox",
            ),
        ),
        migrations.AddConstraint(
            model_name="senderidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("mailbox",),
                name="unique_default_sender_identity_per_mailbox",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["mailbox", "folder", "-created_at"],
                name="emails_mess_mailbox_28e861_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["mailbox", "is_read"], name="emails_mess_mailbox_b2ad41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["thread", "-created_at"], name="emails_mess_thread__c00f5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["direction", "status"], name="emails_mess_directi_42159b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmessage",
            index=models.Index(
                fields=["provider_message_id"], name="emails_mess_provide_7e49c2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("rfc_message_id__isnull", False)),
                fields=("mailbox", "rfc_message_id"),
                name="unique_rfc_message_per_mailbox",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("provider_message_id", ""), _negated=True),
                    ("provider_message_id__isnull", False),
                ),
                fields=("provider", "provider_message_id"),
                name="unique_provider_message_id",
            ),
        ),
        migrations.AddIndex(
            model_name="suppressedaddress",
            index=models.Index(
                fields=["domain", "email"], name="emails_supp_domain__d053e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suppressedaddress",
            index=models.Index(
                fields=["mailbox", "email"], name="emails_supp_mailbox_4b38d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="suppressedaddress",
            index=models.Index(
                fields=["expires_at"], name="emails_supp_expires_301af4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="suppressedaddress",
            constraint=models.UniqueConstraint(
                models.F("domain"),
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("mailbox__isnull", True)),
                name="unique_domain_suppressed_address",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppressedaddress",
            constraint=models.UniqueConstraint(
                models.F("domain"),
                models.F("mailbox"),
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("mailbox__isnull", False)),
                name="unique_mailbox_suppressed_address",
            ),
        ),
        migrations.AddIndex(
            model_name="usermailboxaccess",
            index=models.Index(
                fields=["user", "access_type", "is_active"],
                name="mailboxes_u_user_id_15b9ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usermailboxaccess",
            index=models.Index(
                fields=["expires_at"], name="mailboxes_u_expires_9812b8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usermailboxaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("access_type", "mailbox"),
                        ("domain__isnull", True),
                        ("mailbox__isnull", False),
                    ),
                    models.Q(
                        ("access_type", "domain"),
                        ("domain__isnull", False),
                        ("mailbox__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="access_target_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="usermailboxaccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(("access_type", "mailbox"), ("is_active", True)),
                fields=("user", "mailbox"),
                name="unique_user_mailbox_access",
            ),
        ),
        migrations.AddConstraint(
            model_name="usermailboxaccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(("access_type", "domain"), ("is_active", True)),
                fields=("user", "domain"),
                name="unique_user_domain_access",
            ),
        ),
    ]
