# Generated by Codex on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hedwig", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="file",
            field=models.URLField(blank=True),
        ),
    ]
