# Generated by Django 6.0.6 on 2026-06-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hedwig", "0003_alter_emailattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="checksum_sha256",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="content_disposition",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="file",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="storage_key",
            field=models.CharField(
                blank=True,
                help_text="Object storage key/path for provider-independent access.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="body_html",
            field=models.TextField(blank=True, help_text="HTML part", null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="body_text",
            field=models.TextField(blank=True, help_text="Plain-text part", null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="envelope_recipient",
            field=models.EmailField(
                blank=True,
                help_text="SMTP RCPT TO that caused delivery to this mailbox.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="envelope_sender",
            field=models.EmailField(
                blank=True,
                help_text="SMTP MAIL FROM / return-path address.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="raw_mime_url",
            field=models.URLField(
                blank=True,
                help_text="Object-storage URL for the raw MIME source, if retained.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="reply_to",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="snippet",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=998, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessageuserstate",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="emailrecipient",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="emailrecipient",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="emailrecipient",
            name="provider_recipient_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="emailthread",
            name="normalized_subject",
            field=models.CharField(blank=True, max_length=998, null=True),
        ),
        migrations.AlterField(
            model_name="emailthread",
            name="root_message_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Message-ID that started the conversation, when known.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="forward_to",
            field=models.EmailField(
                blank=True,
                help_text="If set, incoming mail is also forwarded to this external address",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="provider_sender_id",
            field=models.CharField(
                blank=True,
                help_text="Provider-side sender or stream identifier if applicable.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="reply_to",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="signature_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailbox",
            name="signature_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailboxalias",
            name="display_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="mailboxalias",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="outboundsendattempt",
            name="error_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="outboundsendattempt",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="outboundsendattempt",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="outboundsendattempt",
            name="provider_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="outboundsendattempt",
            name="request_payload",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="outboundsendattempt",
            name="response_payload",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="senderidentity",
            name="display_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="senderidentity",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="senderidentity",
            name="reply_to",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="senderidentity",
            name="signature_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="senderidentity",
            name="signature_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="suppressedaddress",
            name="reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="suppressedaddress",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="unsubscribe, bounce, complaint, admin, import, etc.",
                max_length=100,
                null=True,
            ),
        ),
    ]
