# Generated by Django 6.0.6 on 2026-06-14 13:13

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hedwig", "0004_alter_emailattachment_checksum_sha256_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("is_favorite", models.BooleanField(default=False)),
                ("times_contacted", models.PositiveIntegerField(default=0)),
                ("last_contacted_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="hedwig.mailbox",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "emails_contact",
                "ordering": ["-last_contacted_at", "name"],
                "indexes": [
                    models.Index(
                        fields=["mailbox", "name"],
                        name="emails_cont_mailbox_889cc3_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("mailbox"),
                        django.db.models.functions.text.Lower("email"),
                        name="unique_contact_per_mailbox",
                    )
                ],
            },
        ),
    ]
