# Generated by Django 6.0.6 on 2026-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hedwig", "0005_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("bounced", "Bounced"),
                    ("opened", "Opened"),
                    ("clicked", "Clicked"),
                    ("spam", "Spam"),
                    ("draft", "Draft"),
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("failed", "Failed"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="received",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="emailrecipient",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("bounced", "Bounced"),
                    ("opened", "Opened"),
                    ("clicked", "Clicked"),
                    ("spam", "Spam"),
                    ("draft", "Draft"),
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("failed", "Failed"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="queued",
                max_length=15,
            ),
        ),
    ]
