# Generated by Django 6.0.6 on 2026-06-16 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hedwig", "0006_alter_emailmessage_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailbox",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Mailbox",
                "verbose_name_plural": "Mailboxes",
            },
        ),
    ]
