# Generated by Django 6.0.6 on 2026-06-28 16:26

from django.db import migrations, models


def backfill_is_important(apps, schema_editor):
    """Promote the legacy ``metadata.is_important`` flag to the new column."""
    EmailMessageUserState = apps.get_model("hedwig", "EmailMessageUserState")
    EmailMessageUserState.objects.filter(metadata__is_important=True).update(
        is_important=True
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("hedwig", "0007_alter_mailbox_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessageuserstate",
            name="is_important",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill_is_important, noop_reverse),
    ]
