# Generated by Django 6.0.6 on 2026-08-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedwig", "0008_emailmessageuserstate_is_important"),
        ("providers", "0005_alter_deliveryevent_link_url_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mailbox",
            constraint=models.UniqueConstraint(
                models.F("domain"),
                condition=models.Q(("is_catch_all", True)),
                name="unique_catch_all_mailbox_per_domain",
            ),
        ),
    ]
