# Generated by Django 6.0.6 on 2026-06-12 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hedwig", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label, e.g. 'AWS SES – US East'",
                        max_length=100,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("aws_ses", "Amazon SES"),
                            ("postmark", "Postmark"),
                            ("mailgun", "Mailgun"),
                            ("sendgrid", "SendGrid"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "provider_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider-side account, server, stream, or tenant identifier.",
                        max_length=255,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Provider region when applicable, e.g. 'us-east-1'.",
                        max_length=100,
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        blank=True,
                        help_text="Override provider API base URL for regions or private endpoints.",
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider API credentials. Prefer a vault reference in production.",
                    ),
                ),
                (
                    "credential_reference",
                    models.CharField(
                        blank=True,
                        help_text="Secret manager key/path for production credentials.",
                        max_length=255,
                    ),
                ),
                (
                    "webhook_signing_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret used to validate inbound provider webhooks.",
                        max_length=255,
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Feature flags such as inbound, open_tracking, dedicated_ip.",
                    ),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        blank=True,
                        help_text="Fallback sender used for provider health checks.",
                        max_length=254,
                    ),
                ),
                (
                    "max_send_per_day",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("is_sandbox", models.BooleanField(default=False)),
                ("last_health_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_health_check_error", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific data that does not deserve a dedicated column.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Provider",
                "verbose_name_plural": "Email Providers",
                "db_table": "providers_emailprovider",
                "ordering": ["provider_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["provider_type", "is_active"],
                        name="providers_e_provide_0ed3e0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Root domain only, e.g. 'acme.com' (no @ or subdomain prefix)",
                        max_length=253,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("failed", "Verification Failed"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "provider_domain_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider-side domain identifier for reconciliation.",
                        max_length=255,
                    ),
                ),
                ("outbound_enabled", models.BooleanField(default=True)),
                ("inbound_enabled", models.BooleanField(default=True)),
                ("tracking_enabled", models.BooleanField(default=False)),
                (
                    "return_path_domain",
                    models.CharField(
                        blank=True,
                        help_text="Custom bounce/return-path domain when supported.",
                        max_length=253,
                    ),
                ),
                (
                    "tracking_domain",
                    models.CharField(
                        blank=True,
                        help_text="Custom click/open tracking domain when supported.",
                        max_length=253,
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        blank=True,
                        help_text="TXT record value used by provider to verify domain ownership",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dns_records",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Required DNS records as returned by the provider. Example: { 'spf': '...', 'dkim': {...}, 'mx': [...] }",
                    ),
                ),
                (
                    "inbound_route",
                    models.CharField(
                        blank=True,
                        help_text="Inbound webhook route registered with the provider (auto-set on save)",
                        max_length=255,
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Domain-specific shared secret used by inbound routes.",
                        max_length=255,
                    ),
                ),
                (
                    "max_send_per_day",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("dns_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Provider responsible for sending/receiving on this domain",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domains",
                        to="providers.emailprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
                "db_table": "domains_domain",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProviderWebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_event_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider event ID used for idempotency.",
                        max_length=255,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="e.g. 'delivery', 'bounce', 'spam_complaint', 'inbound'",
                        max_length=100,
                    ),
                ),
                ("headers", models.JSONField(blank=True, default=dict)),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Full raw payload from the provider"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("signature_valid", models.BooleanField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_logs",
                        to="providers.domain",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_logs",
                        to="providers.emailprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
                "db_table": "providers_webhooklog",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("complained", "Spam Complaint"),
                            ("unsubscribed", "Unsubscribed"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_event_id", models.CharField(blank=True, max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("link_url", models.URLField(blank=True)),
                ("recipient", models.EmailField(blank=True, max_length=254)),
                ("occurred_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_events",
                        to="hedwig.emailmessage",
                    ),
                ),
                (
                    "raw_webhook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_events",
                        to="providers.providerwebhooklog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Event",
                "verbose_name_plural": "Delivery Events",
                "db_table": "providers_deliveryevent",
                "ordering": ["occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyDomainSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_send_logs",
                        to="providers.domain",
                    ),
                ),
            ],
            options={
                "db_table": "providers_dailydomainsendlog",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "date"), name="unique_domain_send_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DomainDnsRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("CNAME", "CNAME"),
                            ("MX", "MX"),
                            ("TXT", "TXT"),
                        ],
                        max_length=10,
                    ),
                ),
                ("host", models.CharField(max_length=253)),
                ("value", models.TextField()),
                ("priority", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ttl", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        help_text="spf, dkim, dmarc, mx, return_path, tracking, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dns_record_set",
                        to="providers.domain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain DNS Record",
                "verbose_name_plural": "Domain DNS Records",
                "db_table": "providers_domaindnsrecord",
                "ordering": ["domain__name", "purpose", "record_type", "host"],
                "indexes": [
                    models.Index(
                        fields=["domain", "status"],
                        name="providers_d_domain__341b8b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "record_type", "host", "value", "purpose"),
                        name="unique_dns_requirement_per_domain",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(
                fields=["provider", "status"], name="domains_dom_provide_8cf239_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(
                fields=["inbound_enabled", "outbound_enabled", "is_active"],
                name="domains_dom_inbound_c9cdee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providerwebhooklog",
            index=models.Index(
                fields=["status", "received_at"], name="providers_w_status_1555fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providerwebhooklog",
            index=models.Index(
                fields=["provider", "event_type"], name="providers_w_provide_b8748e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerwebhooklog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_event_id", ""), _negated=True),
                fields=("provider", "provider_event_id"),
                name="unique_provider_webhook_event",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryevent",
            index=models.Index(
                fields=["event_type", "occurred_at"],
                name="providers_d_event_t_31ed12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryevent",
            index=models.Index(
                fields=["recipient", "event_type"],
                name="providers_d_recipie_b6510d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_event_id", ""), _negated=True),
                fields=("message", "event_type", "recipient", "provider_event_id"),
                name="unique_delivery_event_per_provider_event",
            ),
        ),
    ]
