# Generated by Django 6.0.6 on 2026-06-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailprovider",
            name="api_base_url",
            field=models.URLField(
                blank=True,
                help_text="Override provider API base URL for regions or private endpoints.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailprovider",
            name="capabilities",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Feature flags such as inbound, open_tracking, dedicated_ip.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailprovider",
            name="credential_reference",
            field=models.CharField(
                blank=True,
                help_text="Secret manager key/path for production credentials.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailprovider",
            name="credentials",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider API credentials. Prefer a vault reference in production.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailprovider",
            name="default_from_email",
            field=models.EmailField(
                blank=True,
                help_text="Fallback sender used for provider health checks.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailprovider",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-specific data that does not deserve a dedicated column.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailprovider",
            name="provider_account_id",
            field=models.CharField(
                blank=True,
                help_text="Provider-side account, server, stream, or tenant identifier.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailprovider",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Provider region when applicable, e.g. 'us-east-1'.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailprovider",
            name="webhook_signing_secret",
            field=models.CharField(
                blank=True,
                help_text="Secret used to validate inbound provider webhooks.",
                max_length=255,
                null=True,
            ),
        ),
    ]
