# Generated by Django 6.0.6 on 2026-06-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0002_alter_emailprovider_api_base_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="dns_records",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Required DNS records as returned by the provider. Example: { 'spf': '...', 'dkim': {...}, 'mx': [...] }",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="inbound_route",
            field=models.CharField(
                blank=True,
                help_text="Inbound webhook route registered with the provider (auto-set on save)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="provider_domain_id",
            field=models.CharField(
                blank=True,
                help_text="Provider-side domain identifier for reconciliation.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="return_path_domain",
            field=models.CharField(
                blank=True,
                help_text="Custom bounce/return-path domain when supported.",
                max_length=253,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="tracking_domain",
            field=models.CharField(
                blank=True,
                help_text="Custom click/open tracking domain when supported.",
                max_length=253,
                null=True,
            ),
        ),
    ]
