# Generated by Django 6.0.6 on 2026-06-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "providers",
            "0003_alter_domain_dns_records_alter_domain_inbound_route_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaindnsrecord",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="domaindnsrecord",
            name="purpose",
            field=models.CharField(
                blank=True,
                help_text="spf, dkim, dmarc, mx, return_path, tracking, etc.",
                max_length=50,
                null=True,
            ),
        ),
    ]
