# Generated by Django 6.0.6 on 2026-06-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0004_alter_domaindnsrecord_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryevent",
            name="link_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryevent",
            name="recipient",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="domaindnsrecord",
            name="last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailprovider",
            name="last_health_check_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="providerwebhooklog",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="providerwebhooklog",
            name="headers",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="providerwebhooklog",
            name="provider_event_id",
            field=models.CharField(
                blank=True,
                help_text="Provider event ID used for idempotency.",
                max_length=255,
                null=True,
            ),
        ),
    ]
