# Generated by Django 6.0.6 on 2026-06-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
