# Generated by Django 6.0.6 on 2026-06-12 18:19

import accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_avatar_url"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.manager.UserManager()),
            ],
        ),
    ]
